### ISSUE TITLE
error making pdf

### ISSUE THREAD

**Issue by ziodos** [tai271828/pyinvoicer#7]
this error occurs after I installed pyinvoicer and tried to run it with default yaml file that you provided under examples folder , any ideas about this ?
WARNING:weasyprint:Ignored `alt: &#34` at 67:3, unknown property.
WARNING:weasyprint:Error: Expected ':' after declaration name, got ident. at 67:21.

**Comment by tai271828** [comment]
Hi @ziodos ,

Thank you for reporting this issue. The warning message is caused by jinja2 to render the html template incorrectly. `&#34` is the "quote marker" in html ascii code, and weasyprint detects this potentially incorrect rendering when rendering pdf from html. However, this warning message should not impact your pdf output. Please feel free to use pyinvoicer.

Besides, I have resolved the warning message. You may fetch the latest code from the main branch of pyinvoicer github repository, or download [the latest release (0.0.3) from PyPI](https://pypi.org/project/pyinvoicer). Enjoy it!
